# Generated by Django 4.2 on 2023-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_article_category_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englisharticle',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='englisharticle',
            name='title',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
